# Basic Site Settings
locale: "en-US"
title: "Junteng Liu"
title_separator: "-"
subtitle: ""
name: "Junteng Liu"
description: "First-year PhD candidate at HKUST NLP Group"
url: "https://ezueaamet.github.io"
baseurl: "/LJT-Homepage"
repository: "ezueaamet/LJT-Homepage"
teaser:
logo:
masthead_title:
words_per_minute: 200
enable_copy_code_button:
talkcred: false
atom_feed:
  path:
  hidden: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
og:
  image:
  image_alt:
  site_name:
analytics:
  provider: false
footer:
  copyright: "copyright 2026"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"
site:
  type: Website
  name:
  site_url:

# Site Author
author:
  name: "Junteng Liu"
  avatar:
  bio: "First-year PhD candidate at HKUST NLP Group. Research focuses on NLP and ML."
  location:
  employer:
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "Vicent0205"
  google_plus:
  keybase:
  instagram:
  impactlibrary:
  lastfm:
  linkedin:
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter: "junteng88716710"
  vine:
  weibo:
  xing:
  youtube:
  wikipedia:
  email: "jliugi@connect.ust.hk"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Pagination
paginate: 5
paginate_path: /page:num/

# Outputting
permalink: /:categories/:title/
timezone:

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  startings: []

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Twitter
twitter:
  username: "junteng88716710"
